# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f72c14786a65b18f2eb97bb46e75875cd526c2e986c8b1297551dfc30832c083ad694646dc02c37d52676c82f642bbb8ad31fc04ea2cb3dcc1670d6206e431a0

test:
  secret_key_base: abd409915d7965a891b62e7dd4eaa2fca71a67c762313446b0bc262f65eb2fd19b45ba26da4bc15f02da20c868c31b938e51516e9e7310da343376b9cf1e4a63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
